services:
  # services
  backend:
    image: otto/backend:local
    container_name: backend
    ports:
      - 8000:8080
    environment:
      - SPRING_DATASOURCE_URL=$BACKEND_DB_JDBC_URL
      - SPRING_DATASOURCE_USERNAME=$DB_USERNAME
      - SPRING_DATASOURCE_URL=$DB_PASSWORD
      - SPRING_JPA_SHOW_SQL=$BACKEND_JPA_LOG_STATEMENTS

  # database
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_DEFAULT_DATABASE
    volumes:
      - db-volume
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

volumes:
  db-volume: