apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: otto
build:
  artifacts:
  - image: backend
    context: .
    jib:
      project: packages/backend
      type: maven
  - image: frontend
    context: .
    docker:
      dockerfile: packages/frontend/Dockerfile

deploy:
  helm:
    releases:
      - name: otto
        namespace: 'otto'
        createNamespace: true
        chartPath: 'helm/otto'
        valuesFiles:
          - helm/otto/values.yaml
        version: 0.1.0
      - name: db
        namespace: 'otto'
        createNamespace: true
        remoteChart: 'postgresql'
        repo: 'https://charts.bitnami.com/bitnami'
        valuesFiles:
          - "helm/dev-db-config.yaml"
        version: 12.2.7
portForward:
  - resourceType: Service
    resourceName: otto
    namespace: otto
    port: 8080
  - resourceType: Service
    resourceName: otto-frontend
    namespace: otto
    port: 80
    localPort: 3000