---
server.port: 8083
# default profile
spring:
  profiles:
    default: local
  devtools.add-properties: false
  # database-connection
  datasource:
    driver-class-name: org.postgresql.Driver
  # jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  # liquibase
  liquibase:
    enabled: false
    change-log: 'classpath:db-changelog.yml'
    drop-first: false
custom:
  model-matching-options:
    day-matcher:
      source: Day
      target: DayEntity
    dayEntity-matcher:
      source: DayEntity
      target: Day
---
spring.config.activate.on-profile: local

spring:
  devtools.add-properties: true
  # database-connection
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: backend
    password: backend
  liquibase.contexts: fixtures
---
spring.config.activate.on-profile: docker
