---
# default profile
spring:
  profiles:
    default: dev
  # database-connection
  datasource:
    driver-class-name: org.postgresql.Driver
  # jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  # liquibase
  liquibase:
    enabled: true
    change-log: 'classpath:db-changelog.yml'
    drop-first: false
---
spring.config.activate.on-profile: dev

spring:
  # database-connection
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: liquibase
    password: liquibase
  jpa.show-sql: true
---
spring.config.activate.on-profile: docker
