---
# default profile
spring:
  profiles:
    default: local
  # database-connection
  datasource:
    driver-class-name: org.postgresql.Driver
  # jpa
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.format_sql: true
  # liquibase
  liquibase:
    enabled: true
    change-log: 'classpath:db-changelog.yml'
    drop-first: false
---
spring.config.activate.on-profile: local

spring:
  # database-connection
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: backend
    password: backend
  liquibase.contexts: fixtures
---
spring.config.activate.on-profile: docker
