@startuml BusinessModels

object event
object day
object room
object timeslotSize
object timeslot
object session
object style

event : name = "Name of the Event/Conference"
event : description = "Description of the Event/Conference"
event : startDate = "Start Date of the Event/Conference"
event : endDate = "End Date of the Event/Conference"
event : style = style
event : days = day[]
event : timeslotSizes = timeslotSizes[]

day : date = "Date of the Day"
day : note = "A note for special days"
day : rooms = room[]

room : name = "Name of the Room"
room : timeslots = timeslot[]

timeslotSize : size = integer
timeslotSize : timeslots = timeslot[]

timeslot : size = timeslotSize
timeslot : startDate = "Start Date of the Timeslot"
timeslot : endDate = "End Date of the Timeslot"
timeslot : room = room

session : title = "Title of the Session"
session : description = "Description of the Session"
session : speakers = "Speakers of the Session"
session : timeslot = timeslot

style : name = "Name of the Style"
style : description = "Description of the Style"
style : color = "Color of the Style"
style : textColor = "Text Color of the Style"
style : events = event[]
style : image = "Image of the Style"

event --> day
event --> style
event --* timeslotSize
event --> session

day --> room

room --> timeslot
timeslot <-- session

@enduml