---
openapi: 3.0.3
info:
  title: "otto-api"
  description: "otto rest api"
  version: 0.0.1

components:
  schemas:
    empty:
      $ref: 'schemas/empty.yml'
    error:
      $ref: 'schemas/error.yml'
    event:
      $ref: 'schemas/event.yml'
    style:
      $ref: 'schemas/style.yml'
    sponsor:
      $ref: 'schemas/sponsor.yml'
    day:
      $ref: 'schemas/day.yml'
    room:
      $ref: 'schemas/room.yml'
    session:
      $ref: 'schemas/session.yml'
    timeslot:
      $ref: 'schemas/timeslot.yml'
    timeslotSize:
      $ref: 'schemas/timeslot-size.yml'

paths:
  /events:
    $ref: 'paths/events.yml'
  /events/{id}:
    $ref: 'paths/event-by-id.yml'
  /rooms:
    $ref: 'paths/rooms.yml'
  /rooms/{id}:
    $ref: 'paths/room-by-id.yml'
  /sessions:
    $ref: 'paths/sessions.yml'
  /sessions/{id}:
    $ref: 'paths/session-by-id.yml'