apiVersion: v1
kind: Service
metadata:
  name: {{ include "otto.fullname" . }}-frontend
  labels:
    {{- include "otto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otto.selectorLabelsFrontend" . | nindent 4 }}
