apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.spring.secrets.dbPassword | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.spring.secrets.dbUser | b64enc }}