apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  SPRING_DATASOURCE_PASSWORD: {{ .Values.global.postgresql.auth.password | b64enc }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.global.postgresql.auth.username | b64enc }}