apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: otto-db
deploy:
  helm:
    releases:
      - name: db
        namespace: 'otto'
        createNamespace: true
        remoteChart: 'postgresql'
        repo: 'https://charts.bitnami.com/bitnami'
        valuesFiles:
          - "dev-db-config.yaml"
